id: vllm-llama3
base_config:
  region: us-chicago-1
  llm_server_type: vllm
  data:
    - prompt_tokens=128,output_tokens=1024
    - prompt_tokens=1024,output_tokens=128
    - prompt_tokens=512,output_tokens=512
    - prompt_tokens=256,output_tokens=2048
    - prompt_tokens=2048,output_tokens=256
    - prompt_tokens=1024,output_tokens=1024
    - prompt_tokens=512,output_tokens=4096
    - prompt_tokens=4096,output_tokens=512
    - prompt_tokens=2048,output_tokens=2048
configs:
  - model: meta-llama/Llama-3.1-8B-Instruct
    gpu: H100!
  - model: meta-llama/Llama-3.1-8B-Instruct
    gpu: H100!
    data:
      - prompt_tokens=128,output_tokens=1024
      - prompt_tokens=1024,output_tokens=128
      - prompt_tokens=512,output_tokens=512
      - prompt_tokens=256,output_tokens=2048
      - prompt_tokens=2048,output_tokens=256
      - prompt_tokens=1024,output_tokens=1024
      - prompt_tokens=512,output_tokens=4096
      - prompt_tokens=4096,output_tokens=512
      - prompt_tokens=2048,output_tokens=2048
      - prompt_tokens=8192,output_tokens=512
      - prompt_tokens=16384,output_tokens=512
      - prompt_tokens=32768,output_tokens=512
    llm_server_config:
      extra_args: ["--quantization", "fp8"]
  - model: RedHatAI/Meta-Llama-3.1-8B-Instruct-quantized.w4a16
    gpu: H100!

  - model: meta-llama/Llama-3.1-70B-Instruct
    gpu: H100!:8
    llm_server_config:
      - extra_args: ["--tensor-parallel-size", "8"]
      - extra_args: ["--tensor-parallel-size", "8", "--quantization", "fp8"]
  - model: RedHatAI/Meta-Llama-3-70B-Instruct-quantized.w4a16
    gpu: H100!:8
    llm_server_config:
      extra_args: ["--tensor-parallel-size", "8"]
