id: tensorrt-llm-llama3
repeats: 1
base_config:
  region: us-chicago-1
  llm_server_type: tensorrt-llm
  data:
    - prompt_tokens=128,output_tokens=1024
    - prompt_tokens=1024,output_tokens=128
    - prompt_tokens=512,output_tokens=512
configs:
  - model: meta-llama/Llama-3.1-8B-Instruct
    gpu: H100
