id: vllm
repeats: 3
base_config:
  region: us-chicago-1
  llm_server_type: vllm
  data:
    - prompt_tokens=256,generated_tokens=4096
    - prompt_tokens=4096,generated_tokens=256
    - prompt_tokens=2048,generated_tokens=2048
configs:
  # Zeta benchmarks
  - model: zed-industries/zeta
    gpu: H100
    llm_server_config:
      tokenizer: Qwen/Qwen2.5-Coder-7B-Instruct
  - model: zed-industries/zeta
    gpu: H100
    llm_server_config:
      tokenizer: Qwen/Qwen2.5-Coder-7B-Instruct
      extra_args: ["--kv-cache-dtype", "fp8_e5m2"]

  # Llama-3.3-70B benchmarks
  - model: meta-llama/Llama-3.3-70B-Instruct
    gpu: H100:4
    llm_server_config:
      extra_args: ["--tensor-parallel-size", "4", "--max-model-len", "8192"]
  - model: meta-llama/Llama-3.3-70B-Instruct
    gpu: H100:4
    llm_server_config:
      extra_args:
        [
          "--tensor-parallel-size",
          "4",
          "--max-model-len",
          "8192",
          "--quantization",
          "fp8",
        ]

  # DeepSeek-V3 benchmarks
  - model: cognitivecomputations/DeepSeek-V3-0324-AWQ
    gpu: H100:8
    llm_server_config:
      extra_args:
        [
          "--tensor-parallel-size",
          "8",
          "--max-model-len",
          "8192",
          "--gpu-memory-utilization",
          "0.95",
          "--dtype",
          "half",
          "--trust-remote-code",
        ]
      env_vars:
        VLLM_USE_V1: "0"
        VLLM_WORKER_MULTIPROC_METHOD: spawn
        VLLM_MARLIN_USE_ATOMIC_ADD: "1"
