id: sglang
files:
  # Can't get DeepSeek to work on SGLang yet. Having the same issue as:
  # https://github.com/sgl-project/sglang/issues/6054
  # - deepseek.yaml
  - gemma3.yaml
  - llama3.yaml
  - mistral.yaml
  - qwen.yaml
  - zeta.yaml
