id: sglang
files:
  # Can't get DeepSeek to work on SGLang yet. Having the same issue as:
  # https://github.com/sgl-project/sglang/issues/6054
  # - deepseek.yaml
  - gemma3.yaml
  - llama3.yaml
  - mistral.yaml
  # SGLang 8xH100 almost always runs out of memory when trying to load Qwen3-235B-A22B.
  # - qwen.yaml
  - zeta.yaml
