id: sglang-deepseek
base_config:
  region: us-chicago-1
  llm_server_type: sglang
  data:
    - prompt_tokens=128,output_tokens=1024
    - prompt_tokens=1024,output_tokens=128
    - prompt_tokens=512,output_tokens=512
  llm_server_config:
    extra_args:
      [
        "--chat-template",
        "/home/no-system-prompt.jinja",
        "--tp",
        "8",
        "--context-length",
        "8192",
        "--dtype",
        "half",
        "--trust-remote-code",
      ]
  model: cognitivecomputations/DeepSeek-V3-0324-AWQ
configs:
  - gpu: H100:8
  # - gpu: B200:8
  #   region: us-ashburn-1
