id: sglang-gemma3
base_config:
  region: us-chicago-1
  llm_server_type: sglang
  llm_server_config:
    extra_args: ["--chat-template", "/home/no-system-prompt.jinja"]
  data:
    - prompt_tokens=128,output_tokens=1024
    - prompt_tokens=1024,output_tokens=128
    - prompt_tokens=512,output_tokens=512
configs:
  - model: google/gemma-3-4b-it
    gpu:
      - H100
      - A10
  - model: google/gemma-3-4b-it
    gpu: L40S
    region: us-ashburn-1

  - model: google/gemma-3-12b-it
    gpu: H100
  - model: google/gemma-3-27b-it
    gpu: H100
