id: sglang-qwen
base_config:
  region: us-chicago-1
  llm_server_type: sglang
  data:
    - prompt_tokens=128,output_tokens=1024
    - prompt_tokens=1024,output_tokens=128
    - prompt_tokens=512,output_tokens=512
    - prompt_tokens=256,output_tokens=2048
    - prompt_tokens=2048,output_tokens=256
    - prompt_tokens=1024,output_tokens=1024
    - prompt_tokens=512,output_tokens=4096
    - prompt_tokens=4096,output_tokens=512
    - prompt_tokens=2048,output_tokens=2048
configs:
  - model: Qwen/Qwen3-235B-A22B
    gpu: H100!:8
    llm_server_config:
      - extra_args: ["--tp", "8", "--reasoning-parser", "qwen3"]

      # SGLang 8xH100 runs out of memory when loading the quantized model
      # - extra_args:
      #     ["--tp", "8", "--reasoning-parser", "qwen3", "--quantization", "fp8"]
